#!/usr/bin/env zsh
set -euo pipefail

pushd $DOTFILES > /dev/null

for folder in ${(s:,:)STOW_FOLDERS}; do
    echo "Removing $folder"
    if [[ "$folder" == "etc" || "$folder" == "usr" ]]; then
        sudo stow -Dvt / "$folder"
    else
        stow -Dvt "$HOME" "$folder"
    fi
done

popd > /dev/null

