#!/usr/bin/env zsh
set -euo pipefail

pushd $DOTFILES > /dev/null
STOW_FOLDERS="aerospace,alacritty,bin,keyboard-layout,nvim,personal,shell,tmux,work,zsh"


for folder in ${(s:,:)STOW_FOLDERS}; do
    echo "Removing $folder"
    stow -Dvt "$HOME" "$folder"
done

popd > /dev/null

