#!/usr/bin/env zsh
set -euo pipefail

pushd $DOTFILES > /dev/null

for folder in ${(s:,:)STOW_FOLDERS}; do
    echo "Removing $folder"
    if [[ "$folder" == "rsi-antidote" ]]; then
        unlink "$HOME/qmk_firmware/keyboards/zsa/moonlander/keymaps/rillyv_zsa_moonlander"
        sudo unlink "/usr/share/xkeyboard-config-2/symbols/rillyv-colemak"
    elif [[ "$folder" == "etc" ]]; then
        sudo stow -Dvt / "$folder"
    else
        stow -Dvt "$HOME" "$folder"
    fi
done

popd > /dev/null

